// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/michelpessoa/desafioCloudRun/configs"
	"github.com/michelpessoa/desafioCloudRun/internal/infra/place"
	"github.com/michelpessoa/desafioCloudRun/internal/infra/place/viacep"
	"github.com/michelpessoa/desafioCloudRun/internal/infra/weather"
	"github.com/michelpessoa/desafioCloudRun/internal/infra/weather/weatherapi"
	"github.com/michelpessoa/desafioCloudRun/internal/usecase"
	"github.com/michelpessoa/desafioCloudRun/internal/web/handler"
	"path/filepath"
	"runtime"
)

// Injectors from wire.go:

func provideGetPlaceForecastUC() usecase.GetPlaceForecast {
	viaCep := viacep.NewViaCep()
	config := provideConfig()
	weatherApi := weatherapi.NewWeatherAPI(config)
	getPlaceForecast := usecase.NewGetPlaceForecastUseCase(viaCep, weatherApi)
	return getPlaceForecast
}

func NewGetPlaceTemperaturesHandler() handler.GetPlaceTemperaturesHandler {
	getPlaceForecast := provideGetPlaceForecastUC()
	getPlaceTemperaturesHandler := handler.NewGetPlaceTemperaturesHandler(getPlaceForecast)
	return getPlaceTemperaturesHandler
}

// wire.go:

func provideConfig() *configs.Config {
	_, currentFile, _, ok := runtime.Caller(0)
	if !ok {
		panic("Erro ao obter informações do arquivo.")
	}
	goDir := filepath.Dir(currentFile)

	config, err := configs.LoadConfig(goDir)
	if err != nil {
		panic(err)
	}
	return config
}

var setPlaceProviderInterface = wire.NewSet(viacep.NewViaCep, wire.Bind(new(place.PlaceProviderInterface), new(*viacep.ViaCep)))

var setWeatherProviderInterface = wire.NewSet(
	provideConfig, weatherapi.NewWeatherAPI, wire.Bind(new(weather.WeatherProviderInterface), new(*weatherapi.WeatherApi)),
)
